# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Benefiter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Benefiter

pod 'RxSwift'
pod 'RxCocoa'

end
